---
- name: Automatizacion de servidores Ubuntu
  hosts: servidores
  become: yes
  tasks:
    - name: 1. Actualizar paquetes APT
      apt:
        update_cache: yes
        upgrade: dist

    - name: 2. Crear el usuario itla
      user:
        name: itla
        state: present
        shell: /bin/bash

    - name: 3. Crear la carpeta app
      file:
        path: /app
        state: directory
        mode: '0755'

    - name: 4. Crear archivo hola.txt en la carpeta app
      copy:
        dest: /app/hola.txt
        content: "Hola desde Ansible para el ITLA\n"

    - name: 5. Instalar cowsay y htop
      apt:
        name:
          - cowsay
          - htop
        state: present